image:
  file: Dockerfile
ports:
- port: 8000
  onOpen: open-preview
tasks:
  - init: composer install
    command: echo "Hallo"
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
        cd /etc/apache2/users/
        nano dld.conf
        chmod 644 dld.conf
        nano /etc/apache2/httpd.conf
        LoadModule authz_core_module libexec/apache2/mod_authz_core.so
        LoadModule authz_host_module libexec/apache2/mod_authz_host.so
        LoadModule userdir_module libexec/apache2/mod_userdir.so
        /private/etc/apache2/extra/httpd-userdir.conf
        nano /etc/apache2/extra/httpd-userdir.conf
        /private/etc/apache2/users/*.conf
        apachectl restart
