image:
  file: Dockerfile
ports:
  - port: 3406
    onOpen: open-preview
tasks:
  - init: composer install
    command: echo "Hello"
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log;
