<?php

/**
 * @file
 * Contains bolthunter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bolthunter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bolthunter module.
    case 'help.page.bolthunter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bolthunter Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bolthunter_theme() {
  return [
    'bolthunter' => [
      'render element' => 'children',
    ],
  ];
}
